all:
	g++ `pkg-config --libs --cflags jubatus_core` -I/opt/jubatus/include -L/opt/jubatus/lib test.cpp -o test
	g++ `pkg-config --libs --cflags jubatus_core` -I/opt/jubatus/include -L/opt/jubatus/lib test_hamming.cpp -o test_hamming
