@echo off
:START
SETLOCAL
SET GENRAND_CHARS=%1
SET GENRAND_CALLBACK=SHOWRESULT
GOTO GENRAND

:SHOWRESULT
ECHO %GENRAND_RESULT%
GOTO END

:GENRAND
SET GENRAND_RESULT=
:GENRAND_START
SET /A GENRAND_TEMP=%RANDOM%/911
IF "%GENRAND_TEMP%" == "10" SET GENRAND_TEMP=A
IF "%GENRAND_TEMP%" == "11" SET GENRAND_TEMP=B
IF "%GENRAND_TEMP%" == "12" SET GENRAND_TEMP=C
IF "%GENRAND_TEMP%" == "13" SET GENRAND_TEMP=D
IF "%GENRAND_TEMP%" == "14" SET GENRAND_TEMP=E
IF "%GENRAND_TEMP%" == "15" SET GENRAND_TEMP=F
IF "%GENRAND_TEMP%" == "16" SET GENRAND_TEMP=G
IF "%GENRAND_TEMP%" == "17" SET GENRAND_TEMP=H
IF "%GENRAND_TEMP%" == "18" SET GENRAND_TEMP=I
IF "%GENRAND_TEMP%" == "19" SET GENRAND_TEMP=J
IF "%GENRAND_TEMP%" == "20" SET GENRAND_TEMP=K
IF "%GENRAND_TEMP%" == "21" SET GENRAND_TEMP=L
IF "%GENRAND_TEMP%" == "22" SET GENRAND_TEMP=M
IF "%GENRAND_TEMP%" == "23" SET GENRAND_TEMP=N
IF "%GENRAND_TEMP%" == "24" SET GENRAND_TEMP=O
IF "%GENRAND_TEMP%" == "25" SET GENRAND_TEMP=P
IF "%GENRAND_TEMP%" == "26" SET GENRAND_TEMP=Q
IF "%GENRAND_TEMP%" == "27" SET GENRAND_TEMP=R
IF "%GENRAND_TEMP%" == "28" SET GENRAND_TEMP=S
IF "%GENRAND_TEMP%" == "29" SET GENRAND_TEMP=T
IF "%GENRAND_TEMP%" == "30" SET GENRAND_TEMP=U
IF "%GENRAND_TEMP%" == "31" SET GENRAND_TEMP=V
IF "%GENRAND_TEMP%" == "32" SET GENRAND_TEMP=W
IF "%GENRAND_TEMP%" == "33" SET GENRAND_TEMP=X
IF "%GENRAND_TEMP%" == "34" SET GENRAND_TEMP=Y
IF "%GENRAND_TEMP%" == "35" SET GENRAND_TEMP=Z
SET GENRAND_RESULT=%GENRAND_RESULT%%GENRAND_TEMP%
SET /A GENRAND_CHARS=%GENRAND_CHARS%-1
IF %GENRAND_CHARS% LEQ 0 GOTO %GENRAND_CALLBACK%
GOTO GENRAND_START

:END

REM perl -e 'for($i=10;$i<36;$i++){$n=$i+55;print "IF \"%GENRAND_TEMP%\" == \"$i\" SET GENRAND_TEMP=",chr $n,"\n";}'