#!/usr/bin/env python

import itertools
import json
import sys

import asv.benchmark
import six


"""
This script discovers ASV benchmarks from specified directory and lists
fully-qualified benchmark IDs and its parameters.

You can then run the benchmark code directly like:

 $ python -m asv.benchmark run benchmarks mod.method-0 True None /dev/stdout

where arguments for the `run` subcommand are:

 (benchmark_dir, benchmark_id, quick, profile_path, result_file)
"""


if __name__ == '__main__':
    benchmark_dir = sys.argv[1] if len(sys.argv) == 2 else 'benchmarks'

    fp = six.StringIO()
    asv.benchmark.list_benchmarks(benchmark_dir, fp)
    fp.seek(0)
    for benchmark in json.load(fp):
        print('{}'.format(benchmark['name']))
        if benchmark['params']:
            param_iter = enumerate(itertools.product(*benchmark['params']))
            for param_index, param in param_iter:
                pdict = list(zip(benchmark['param_names'], param))
                print('  {}-{}\t Parameters = {}'.format(
                    benchmark['name'], param_index, pdict))
