#!/usr/bin/env python

import sys

import asv.benchmark


"""
This script runs ASV benchmark code directly.
See `asvlist` for details.
"""


if __name__ == '__main__':
    assert 2 <= len(sys.argv)
    benchmark_dir = sys.argv[1] if len(sys.argv) == 3 else 'benchmarks'
    benchmark_id = sys.argv[-1]

    run = asv.benchmark.commands['run']
    run((benchmark_dir, benchmark_id, 'True', 'None', '/dev/stdout'))
