name: Composite Action Example
description: "Composite Action example"

runs:
  using: composite
  steps:
  - id: foo
    run:
      echo "backend=gcp" >> "${GITHUB_OUTPUT}"
    shell: bash
  - if: steps.foo.outputs.backend == 'gcp'
    run: echo "Yes"
    shell: bash
