name: "Auto Notify"

on:
  issues:
    types: [labeled]
  pull_request_target:
    types: [labeled]


jobs:
  auto-notify:
    if: |
        github.repository_owner == 'kmaehashi' &&
        contains('hip|array-api', github.event.label.name)
    env:
      NOTIFY_TARGETS: '{"hip": "@kmaehashi (hip)", "array-api": "@kmaehashi (array-api)"}'
    runs-on: ubuntu-20.04

    steps:
      - name: Find comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
            issue-number: ${{ (github.event_name == 'issues' && github.event.issue.number) || github.event.pull_request.number }}
            body-includes: "<!-- Added by Auto Notify Bot (${{ github.event.label.name }}) -->"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
            issue-number: ${{ (github.event_name == 'issues' && github.event.issue.number) || github.event.pull_request.number }}
            comment-id: ${{steps.fc.outputs.comment-id}}
            edit-mode: replace
            body: |
                <!-- Added by Auto Notify Bot (${{ github.event.label.name }}) -->
                cc/ ${{ fromJSON(env.NOTIFY_TARGETS)[github.event.label.name] }}
