name: github script test

on:
  issue_comment:

jobs:
  close:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          require("@octokit/auth-app");
