name: If condition

on:
  workflow_dispatch:

jobs:
  work:
    runs-on: ubuntu-latest
    steps:
    - id: foo
      run:
        echo "backend=gcp" >> "${GITHUB_OUTPUT}"
    - if: steps.foo.outputs.backend == 'gcp'
      run: echo "Yes"
