name: Matrix Outputs

on:
  workflow_dispatch:

jobs:
  matrix1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #os: ['linux', 'windows']
        os: ['linux']
        python: ['3.10', '3.11']
    steps:
    - run: |
        echo "${{ join(matrix, '__') }}"
        KEY="${{ join(matrix.*, '__') }}"
        VALUE="${RANDOM}"
        jq --arg key "${{ join(matrix.*, '__') }}" --arg value "${RANDOM}"
        cat << _EOF_ > "$(echo ${KEY} | md5sum | awk '{print $1}').json"
        {"${KEY}": "${VALUE}"}
        _EOF_
    - uses: actions/upload-artifact@v3
      with:
        name: matrix-outputs
        path: '*.json'
        retention-days: 1
  reduce:
    needs: matrix1
    runs-on: ubuntu-latest
    outputs:
      values: ${{ steps.values.outputs.values }}
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: matrix-outputs
    - id: values
      run: |
        find .
        jq -s add *.json
        echo "values=$(jq -c -s add *.json)" >> "$GITHUB_OUTPUT"
  matrix2:
    needs: reduce
    runs-on: ${{ fromJSON(needs.reduce.outputs.values)[join(matrix.*, '|')] }}
    strategy:
      matrix:
        #os: ['linux', 'windows']
        os: ['linux']
        python: ['3.10', '3.11']
    env:
      VALUE: ${{ fromJSON(needs.reduce.outputs.values)[format('{0}-{1}', matrix.os, matrix.python)] }}
    steps:
    - run: echo "${VALUE}"
