name: Matrix Outputs

on:
  workflow_dispatch:

jobs:
  matrix1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['linux']
        python: ['3.10', '3.11']
    env:
      MATRIX: ${{ toJSON(matrix) }}
    steps:
    - run: |
        LABEL="${RANDOM}"
        jq -n --arg matrix "${MATRIX}" --arg label "${LABEL}" '{($matrix): ($label)}' > "$(uuidgen).json"
    - uses: actions/upload-artifact@v3
      with:
        name: matrix-labels
        path: '*.json'
        retention-days: 1
  reduce:
    needs: matrix1
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.output.outputs.labels }}
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: matrix-labels
    - id: output
      run: |
        echo "labels=$(jq -c -s add *.json)" >> "$GITHUB_OUTPUT"
  matrix2:
    needs: reduce
    runs-on: ${{ fromJSON(needs.reduce.outputs.labels)[toJSON(matrix)] }}
    strategy:
      matrix:
        os: ['linux']
        python: ['3.10', '3.11']
    steps:
    - run: echo Hello!
