on: workflow_dispatch

jobs:
  my_job:
    strategy:
      max-parallel: 1
      matrix:
        include:
        - owner: "user1"
          repos: ["x", "y"]
        - owner: "user2"
    runs-on: ubuntu-latest
    steps:
    - run: echo '${{ toJSON(matrix) }}'; sleep 10
  second_job:
    strategy:
      max-parallel: 1
      matrix:
        foo: [1,2,3]
        bar: [4,5,6]
    runs-on: ubuntu-latest
    steps:
    - run: echo '${{ toJSON(matrix) }}'; sleep 10
