name: "Release"

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - run: |
        gh release --repo kmaehashi/sandbox view draft
