name: "Rerun"

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    permissions: write-all
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/kmaehashi/sandbox/actions/runs/${{ github.run_id	}}/rerun
