name: "Test"

on: [push, pull_request]

jobs:
  debug:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo cache branch commit = ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.sha }}

      - run: |
          echo ${{toJSON(github)}}
